name: Coverage Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Coverage-on-Ubuntu:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8

      - name: Install Chrome Puppeteer Browser
        run: npx puppeteer browsers install chrome

      - name: Install Firefox Puppeteer Browser
        run: npx puppeteer browsers install firefox

      - name: Run Coverage Testing
        run: npm run coverage

      - name: Codecov
        if: ${{ github.event_name != 'pull_request' && env.CODECOV_TOKEN != '' }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

      - name: Archive PDF output
        uses: actions/upload-artifact@v6
        with:
          name: pdf-output-ubuntu
          path: |
            test/output/*.pdf

  Testing-on-Windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8
      
      - name: Install Chrome Puppeteer Browser
        run: npx puppeteer browsers install chrome

      - name: Install Firefox Puppeteer Browser
        run: npx puppeteer browsers install firefox
        continue-on-error: true

      - name: Run Testing
        run: npm test

      - name: Archive PDF output
        uses: actions/upload-artifact@v6
        with:
          name: pdf-output-windows
          path: |
            test/output/*.pdf

  Testing-on-MacOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8
      
      - name: Install Chrome Puppeteer Browser
        run: npx puppeteer browsers install chrome

      - name: Install Firefox Puppeteer Browser
        run: npx puppeteer browsers install firefox

      - name: Run Coverage Testing
        run: npm run coverage

      - name: Archive PDF output
        uses: actions/upload-artifact@v6
        with:
          name: pdf-output-macos
          path: |
            test/output/*.pdf
